const buttons = [
  {
    code: 'Backquote',
    ruValue: 'ё',
    ruShiftValue: 'Ё',
    enValue: '`',
    enShiftValue: '~',
    width: 40,
  },
  {
    code: 'Digit1',
    ruValue: '1',
    ruShiftValue: '!',
    enValue: '1',
    enShiftValue: '!',
    width: 40,
  },
  {
    code: 'Digit2',
    ruValue: '2',
    ruShiftValue: '"',
    enValue: '2',
    enShiftValue: '@',
    width: 40,
  },
  {
    code: 'Digit3',
    ruValue: '3',
    ruShiftValue: '№',
    enValue: '3',
    enShiftValue: '#',
    width: 40,
  },
  {
    code: 'Digit4',
    ruValue: '4',
    ruShiftValue: ';',
    enValue: '4',
    enShiftValue: '$',
    width: 40,
  },
  {
    code: 'Digit5',
    ruValue: '5',
    ruShiftValue: '%',
    enValue: '5',
    enShiftValue: '%',
    width: 40,
  },
  {
    code: 'Digit6',
    ruValue: '6',
    ruShiftValue: ':',
    enValue: '6',
    enShiftValue: '^',
    width: 40,
  },
  {
    code: 'Digit7',
    ruValue: '7',
    ruShiftValue: '?',
    enValue: '7',
    enShiftValue: '&',
    width: 40,
  },
  {
    code: 'Digit8',
    ruValue: '8',
    ruShiftValue: '*',
    enValue: '8',
    enShiftValue: '*',
    width: 40,
  },
  {
    code: 'Digit9',
    ruValue: '9',
    ruShiftValue: '(',
    enValue: '9',
    enShiftValue: '(',
    width: 40,
  },
  {
    code: 'Digit0',
    ruValue: '0',
    ruShiftValue: ')',
    enValue: '0',
    enShiftValue: ')',
    width: 40,
  },
  {
    code: 'Minus',
    ruValue: '-',
    ruShiftValue: '_',
    enValue: '-',
    enShiftValue: '_',
    width: 40,
  },
  {
    code: 'Equal',
    ruValue: '=',
    ruShiftValue: '+',
    enValue: '=',
    enShiftValue: '+',
    width: 40,
  },
  {
    code: 'Backspace',
    ruValue: '',
    ruShiftValue: '',
    enValue: '',
    enShiftValue: '',
    width: 94,
    command: 'Backspace',
  },
  {
    code: 'Tab',
    ruValue: '\t',
    ruShiftValue: '\t',
    enValue: '\t',
    enShiftValue: '\t',
    width: 48,
    command: 'Tab',
  },
  {
    code: 'KeyQ',
    ruValue: 'й',
    ruShiftValue: 'Й',
    enValue: 'q',
    enShiftValue: 'Q',
    width: 40,
  },
  {
    code: 'KeyW',
    ruValue: 'ц',
    ruShiftValue: 'Ц',
    enValue: 'w',
    enShiftValue: 'W',
    width: 40,
  },
  {
    code: 'KeyE',
    ruValue: 'у',
    ruShiftValue: 'У',
    enValue: 'e',
    enShiftValue: 'E',
    width: 40,
  },
  {
    code: 'KeyR',
    ruValue: 'к',
    ruShiftValue: 'К',
    enValue: 'r',
    enShiftValue: 'R',
    width: 40,
  },
  {
    code: 'KeyT',
    ruValue: 'е',
    ruShiftValue: 'Е',
    enValue: 't',
    enShiftValue: 'T',
    width: 40,
  },
  {
    code: 'KeyY',
    ruValue: 'н',
    ruShiftValue: 'Н',
    enValue: 'y',
    enShiftValue: 'Y',
    width: 40,
  },
  {
    code: 'KeyU',
    ruValue: 'г',
    ruShiftValue: 'Г',
    enValue: 'u',
    enShiftValue: 'U',
    width: 40,
  },
  {
    code: 'KeyI',
    ruValue: 'ш',
    ruShiftValue: 'Ш',
    enValue: 'i',
    enShiftValue: 'I',
    width: 40,
  },
  {
    code: 'KeyO',
    ruValue: 'щ',
    ruShiftValue: 'Щ',
    enValue: 'o',
    enShiftValue: 'O',
    width: 40,
  },
  {
    code: 'KeyP',
    ruValue: 'з',
    ruShiftValue: 'З',
    enValue: 'p',
    enShiftValue: 'P',
    width: 40,
  },
  {
    code: 'BracketLeft',
    ruValue: 'х',
    ruShiftValue: 'Х',
    enValue: '[',
    enShiftValue: '{',
    width: 40,
  },
  {
    code: 'BracketRight',
    ruValue: 'ъ',
    ruShiftValue: 'Ъ',
    enValue: ']',
    enShiftValue: '}',
    width: 40,
  },
  {
    code: 'Backslash',
    ruValue: '\\',
    ruShiftValue: '/',
    enValue: '\\',
    enShiftValue: '|',
    width: 40,
  },
  {
    code: 'Delete',
    ruValue: '',
    ruShiftValue: '',
    enValue: '',
    enShiftValue: '',
    width: 40,
    command: 'Del',
  },
  {
    code: 'CapsLock',
    ruValue: '',
    ruShiftValue: '',
    enValue: '',
    enShiftValue: '',
    width: 100,
    command: 'CapsLock',
  },
  {
    code: 'KeyA',
    ruValue: 'ф',
    ruShiftValue: 'Ф',
    enValue: 'a',
    enShiftValue: 'A',
    width: 40,
  },
  {
    code: 'KeyS',
    ruValue: 'ы',
    ruShiftValue: 'Ы',
    enValue: 's',
    enShiftValue: 'S',
    width: 40,
  },
  {
    code: 'KeyD',
    ruValue: 'в',
    ruShiftValue: 'В',
    enValue: 'd',
    enShiftValue: 'D',
    width: 40,
  },
  {
    code: 'KeyF',
    ruValue: 'а',
    ruShiftValue: 'А',
    enValue: 'f',
    enShiftValue: 'F',
    width: 40,
  },
  {
    code: 'KeyG',
    ruValue: 'п',
    ruShiftValue: 'П',
    enValue: 'g',
    enShiftValue: 'G',
    width: 40,
  },
  {
    code: 'KeyH',
    ruValue: 'р',
    ruShiftValue: 'Р',
    enValue: 'h',
    enShiftValue: 'H',
    width: 40,
  },
  {
    code: 'KeyJ',
    ruValue: 'о',
    ruShiftValue: 'О',
    enValue: 'j',
    enShiftValue: 'J',
    width: 40,
  },
  {
    code: 'KeyK',
    ruValue: 'л',
    ruShiftValue: 'Л',
    enValue: 'k',
    enShiftValue: 'K',
    width: 40,
  },
  {
    code: 'KeyL',
    ruValue: 'д',
    ruShiftValue: 'Д',
    enValue: 'l',
    enShiftValue: 'L',
    width: 40,
  },
  {
    code: 'Semicolon',
    ruValue: 'ж',
    ruShiftValue: 'Ж',
    enValue: ';',
    enShiftValue: ':',
    width: 40,
  },
  {
    code: 'Quote',
    ruValue: 'э',
    ruShiftValue: 'Э',
    enValue: "'",
    enShiftValue: '"',
    width: 40,
  },
  {
    code: 'Enter',
    ruValue: '\n',
    ruShiftValue: '\n',
    enValue: '\n',
    enShiftValue: '\n',
    width: 80,
    command: 'Enter',
  },
  {
    code: 'ShiftLeft',
    ruValue: '',
    ruShiftValue: '',
    enValue: '',
    enShiftValue: '',
    width: 100,
    command: 'Shift',
  },
  {
    code: 'KeyZ',
    ruValue: 'я',
    ruShiftValue: 'Я',
    enValue: 'z',
    enShiftValue: 'Z',
    width: 40,
  },
  {
    code: 'KeyX',
    ruValue: 'ч',
    ruShiftValue: 'Ч',
    enValue: 'x',
    enShiftValue: 'X',
    width: 40,
  },
  {
    code: 'KeyC',
    ruValue: 'с',
    ruShiftValue: 'С',
    enValue: 'c',
    enShiftValue: 'C',
    width: 40,
  },
  {
    code: 'KeyV',
    ruValue: 'м',
    ruShiftValue: 'М',
    enValue: 'v',
    enShiftValue: 'V',
    width: 40,
  },
  {
    code: 'KeyB',
    ruValue: 'и',
    ruShiftValue: 'И',
    enValue: 'b',
    enShiftValue: 'B',
    width: 40,
  },
  {
    code: 'KeyN',
    ruValue: 'т',
    ruShiftValue: 'Т',
    enValue: 'n',
    enShiftValue: 'N',
    width: 40,
  },
  {
    code: 'KeyM',
    ruValue: 'ь',
    ruShiftValue: 'Ь',
    enValue: 'm',
    enShiftValue: 'M',
    width: 40,
  },
  {
    code: 'Comma',
    ruValue: 'б',
    ruShiftValue: 'Б',
    enValue: ',',
    enShiftValue: '<',
    width: 40,
  },
  {
    code: 'Period',
    ruValue: 'ю',
    ruShiftValue: 'Ю',
    enValue: '.',
    enShiftValue: '>',
    width: 40,
  },
  {
    code: 'Slash',
    ruValue: '.',
    ruShiftValue: ',',
    enValue: '/',
    enShiftValue: '?',
    width: 40,
  },
  {
    code: 'ArrowUp',
    ruValue: '',
    ruShiftValue: '',
    enValue: '',
    enShiftValue: '',
    width: 40,
    command: '▲',
  },
  {
    code: 'ShiftRight',
    ruValue: '',
    ruShiftValue: '',
    enValue: '',
    enShiftValue: '',
    width: 80,
    command: 'Shift',
  },
  {
    code: 'ControlLeft',
    ruValue: '',
    ruShiftValue: '',
    enValue: '',
    enShiftValue: '',
    width: 40,
    command: 'Ctrl',
  },
  {
    code: 'MetaLeft',
    ruValue: '',
    ruShiftValue: '',
    enValue: '',
    enShiftValue: '',
    width: 40,
    command: 'Win',
  },
  {
    code: 'AltLeft',
    ruValue: '',
    ruShiftValue: '',
    enValue: '',
    enShiftValue: '',
    width: 40,
    command: 'Alt',
  },
  {
    code: 'Space',
    ruValue: ' ',
    ruShiftValue: ' ',
    enValue: ' ',
    enShiftValue: ' ',
    width: 330,
  },
  {
    code: 'AltRight',
    ruValue: '',
    ruShiftValue: '',
    enValue: '',
    enShiftValue: '',
    width: 40,
    command: 'Alt',
  },
  {
    code: 'ArrowLeft',
    ruValue: '',
    ruShiftValue: '',
    enValue: '',
    enShiftValue: '',
    width: 40,
    command: '◄',
  },
  {
    code: 'ArrowDown',
    ruValue: '',
    ruShiftValue: '',
    enValue: '',
    enShiftValue: '',
    width: 40,
    command: '▼',
  },
  {
    code: 'ArrowRight',
    ruValue: '',
    ruShiftValue: '',
    enValue: '',
    enShiftValue: '',
    width: 40,
    command: '►',
  },
  {
    code: 'ControlRight',
    ruValue: '',
    ruShiftValue: '',
    enValue: '',
    enShiftValue: '',
    width: 34,
    command: 'Ctrl',
  },
];

export default buttons;
